"""Type stubs for the ``addivortes._native`` extension module.

The docstrings of record live on the Rust items (``addivortes-py/src/lib.rs``);
these stubs carry the shapes and types for IDEs and type checkers.
"""

from collections.abc import Sequence
from typing import Any

import numpy as np
from numpy.typing import NDArray

class AddiVortesError(ValueError):
    """An error from the addivortes engine (invalid data, hyperparameters, or state)."""

class AddiVortes:
    """The native model spec: a ConfigSpec JSON payload.

    The ergonomic keyword layer is ``addivortes.AddiVortes`` (pure Python); this
    class carries the payload and nothing else, which is why the shelf reaches
    Python without being enumerated here.
    """

    def __init__(self, spec_json: str) -> None: ...
    @property
    def spec_json(self) -> str: ...
    @property
    def response_family(self) -> str: ...
    def fit(
        self, x: NDArray[np.float64], y: NDArray[np.float64]
    ) -> FittedModel: ...
    def fit_chains(
        self, x: NDArray[np.float64], y: NDArray[np.float64], n_chains: int
    ) -> list[FittedModel]: ...

def validate_spec(spec_json: str) -> None:
    """Validate a spec payload with no data; raises ``AddiVortesError``."""

class FittedModel:
    def predict(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def predict_draws(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def log_likelihood(
        self, x: NDArray[np.float64], y: NDArray[np.float64]
    ) -> NDArray[np.float64]: ...
    def predict_quantiles(
        self, x: NDArray[np.float64], probs: Sequence[float]
    ) -> NDArray[np.float64]: ...
    def prediction_interval(
        self, x: NDArray[np.float64], level: float
    ) -> tuple[NDArray[np.float64], NDArray[np.float64]]: ...
    def credible_interval(
        self, x: NDArray[np.float64], level: float
    ) -> tuple[NDArray[np.float64], NDArray[np.float64]]: ...
    def sigma(self) -> NDArray[np.float64]: ...
    def total_cells(self) -> NDArray[np.float64]: ...
    def variable_inclusion_proportions(self) -> NDArray[np.float64]: ...
    @property
    def in_sample_rmse(self) -> float: ...
    @property
    def n_draws(self) -> int: ...
    @property
    def n_features(self) -> int: ...
    @property
    def response_family(self) -> str: ...
    @property
    def t_df(self) -> float | None: ...
    def warnings(self) -> list[str]: ...
    def to_json(self) -> str: ...
    @staticmethod
    def from_json(payload: str) -> FittedModel: ...
    def save(self, path: str) -> None: ...
    @staticmethod
    def load(path: str) -> FittedModel: ...
    def __reduce__(self) -> tuple[Any, tuple[str]]: ...

def r_hat(chains: Sequence[Sequence[float]]) -> float: ...
def ess_bulk(chains: Sequence[Sequence[float]]) -> float: ...
def ess_tail(chains: Sequence[Sequence[float]]) -> float: ...
def predictive_qq(
    y: NDArray[np.float64],
    fit_draws: NDArray[np.float64],
    s_draws: NDArray[np.float64],
) -> list[float]: ...
