# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_addivortesr_wrappers", use_symbols = TRUE, package_name = "addivortesr")

#' @usage NULL
#' @useDynLib addivortesr, .registration = TRUE
NULL

#' Validate a `ConfigSpec` payload with no data, so R can fail at the point the
#' user wrote the mistake rather than at `fit`. Carries the crate's own message.
#' @noRd
avt_validate_spec <- function(spec_json) invisible(.Call(wrap__avt_validate_spec, spec_json))

#' Fit from a `ConfigSpec` JSON payload.
#'
#' The payload is the whole configuration. This function names no
#' hyperparameter and no shelf item, so a new shelf entry in the crate is
#' reachable from R on rebuild with no change here.
#' @noRd
avt_fit <- function(x, y, spec_json) .Call(wrap__avt_fit, x, y, spec_json)

#' Fit `n_chains` independent chains (seeds derived from the configured
#' seed; chain 1 is bit-identical to a plain `avt_fit`). Returns a list of
#' fitted models.
#' @noRd
avt_fit_chains <- function(x, y, spec_json, n_chains) .Call(wrap__avt_fit_chains, x, y, spec_json, n_chains)

#' Split-R<U+0302> (Vehtari et al. 2021) over a list of equal-length numeric
#' chains.
#' @noRd
avt_r_hat <- function(chains) .Call(wrap__avt_r_hat, chains)

#' Bulk effective sample size (Vehtari et al. 2021).
#' @noRd
avt_ess_bulk <- function(chains) .Call(wrap__avt_ess_bulk, chains)

#' Tail effective sample size (Vehtari et al. 2021).
#' @noRd
avt_ess_tail <- function(chains) .Call(wrap__avt_ess_tail, chains)

#' Predictive-QQ PIT values (sorted ascending): calibration of
#' the heteroscedastic Gaussian predictive N(fit_d(x_i), s_d(x_i)^2)
#' against observed `y`. `fit_draws` and `s_draws` are (n_draws, n_rows)
#' matrices <U+2014> `predict_draws` output and the per-draw error SD broadcast
#' per row. Plot against uniform quantiles (i - 1/2)/n: a straight line is
#' a calibrated model. Shapes are validated here (the crate asserts).
#' @noRd
avt_predictive_qq <- function(y, fit_draws, s_draws) .Call(wrap__avt_predictive_qq, y, fit_draws, s_draws)

FittedModel <- new.env(parent = emptyenv())

FittedModel$predict <- function(x) .Call(wrap__FittedModel__predict, self, x)

FittedModel$predict_draws <- function(x) .Call(wrap__FittedModel__predict_draws, self, x)

FittedModel$log_likelihood <- function(x, y) .Call(wrap__FittedModel__log_likelihood, self, x, y)

FittedModel$predict_quantiles <- function(x, probs) .Call(wrap__FittedModel__predict_quantiles, self, x, probs)

FittedModel$prediction_interval <- function(x, level) .Call(wrap__FittedModel__prediction_interval, self, x, level)

FittedModel$credible_interval <- function(x, level) .Call(wrap__FittedModel__credible_interval, self, x, level)

FittedModel$sigma <- function() .Call(wrap__FittedModel__sigma, self)

FittedModel$total_cells <- function() .Call(wrap__FittedModel__total_cells, self)

FittedModel$variable_inclusion_proportions <- function() .Call(wrap__FittedModel__variable_inclusion_proportions, self)

FittedModel$in_sample_rmse <- function() .Call(wrap__FittedModel__in_sample_rmse, self)

FittedModel$n_draws <- function() .Call(wrap__FittedModel__n_draws, self)

FittedModel$response_family <- function() .Call(wrap__FittedModel__response_family, self)

FittedModel$t_df <- function() .Call(wrap__FittedModel__t_df, self)

FittedModel$n_features <- function() .Call(wrap__FittedModel__n_features, self)

FittedModel$warnings <- function() .Call(wrap__FittedModel__warnings, self)

FittedModel$to_json <- function() .Call(wrap__FittedModel__to_json, self)

FittedModel$from_json <- function(payload) .Call(wrap__FittedModel__from_json, payload)

FittedModel$save <- function(path) invisible(.Call(wrap__FittedModel__save, self, path))

FittedModel$load <- function(path) .Call(wrap__FittedModel__load, path)

#' @export
`$.FittedModel` <- function (self, name) { func <- FittedModel[[name]]; environment(func) <- environment(); func }

#' @export
`[[.FittedModel` <- `$.FittedModel`


